
pattern = (
    'ggbdcgg     g                                          ',
    'eggegge                                                ',
    'gggggdg                                                ',
    'gdgggdg                                                ',
    'gdggggg                                                ',
    'ggggggg                                                ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
)
