
pattern = (
    'ggbdcggg     g                                          ',
    'eggeggeg                                               ',
    'ggggbdgg                                               ',
    'gdgggdgg                                               ',
    'gdgggdcg                                               ',
    'gggggggg                                               ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
)
