
pattern = (
    'ggbdddddcggg                                          ',
    'eggeggeggggg                                          ',
    'ggggbdgggggg                                           ',
    'gdgggdgggggg                                           ',
    'gdgggdcggggg                                           ',
    'gggggggggggg                                           ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
)
