from typing import NamedTuple

from logic.game_objects.action import ActionType

pattern = (
    'abdca      a                                           ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
    '                                                       ',
)


class MapElementConst(NamedTuple):
    path: str
    action_type: ActionType


MapElementsConsts = {'a': MapElementConst('tileGrass_slope.png', ActionType.usual),
                     'b': MapElementConst('tileGrass_slopeLeft.png', ActionType.lifting_up),
                     'c': MapElementConst('tileGrass_slopeRight.png', ActionType.lifting_down),
                     'd': MapElementConst('tileGrass.png', ActionType.usual),
                     'e': '',
                     'f': '',
                     'g': '',
                     'h': '',
                     'i': '',
                     'j': '',
                     'k': '',
                     'l': '',
                     'm': '',
                     'n': '',
                     'o': '',
                     'p': '',
                     'q': '',
                     'r': '',
                     's': '',
                     't': '',
                     'u': '',
                     'v': '',
                     'w': '',
                     'x': '',
                     'y': '',
                     'z': '',
                     '1': '',
                     '2': '',
                     '3': '',
                     '4': '',
                     '5': '',
                     '6': '',
                     '7': '',
                     '8': '',
                     '9': '',
                     '0': '',
                     'A': '',
                     'B': '',
                     'C': '',
                     'D': '',
                     'E': '',
                     'F': '',
                     'G': '',
                     'H': '',
                     'I': '',
                     'J': '',
                     'K': '',
                     'L': '',
                     'M': '',
                     'N': '',
                     }
